---

name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: 'Tests (pytest)'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Run tests
        run: |
          uv run pytest -s -vv --cov=padpo

